### ISSUE TITLE
Documentation for uses within wildfly ISPN

### ISSUE THREAD

**Issue by lucasponce** [jgroups-extras/jgroups-kubernetes#12]
Hello,
In Hawkular we have an use case to use ISPN inside OpenShift.
Reading this post:
http://blog.infinispan.org/2016/08/running-infinispan-cluster-on-openshift.html
seems that jgroups-kubernet is just what we need.
Is there any documentation about a widfly/EAP image that supports this protocol ?
Thanks.

**Comment by slaskawi** [comment]
Hey @lucasponce! 

EAP should work on OpenShift without any problems. Please have a look at [this guide](https://developers.openshift.com/servers/jbosseap/getting-started.html).

Unfortunately I'm not sure about WildFly (the community version of EAP), but I'll check it out and get back to you soon.

**Comment by mwringe** [comment]
That looks to be the documentation for the old cartridge based OpenShift, we are looking more for how to do this in OpenShift v3

**Comment by slaskawi** [comment]
Right, for OSE3 you can find the information here: https://docs.openshift.com/enterprise/3.0/using_images/xpaas_images/eap.html

**Comment by mwringe** [comment]
Do you have documentation for the newer OSE 3.3 release?

Note that we already have our own pods for our setup right now, but they were stateless and didn't need to cluster together. We are now moving towards a stateful approach and we need to figure out how to securely cluster our EAP and Wildfly instances with jgroups/infinispan. 

It looks like http://blog.infinispan.org/2016/08/running-infinispan-cluster-on-openshift.html provides what we need to do, but I don't know if we should just follow what is outlined there or if there is more official documentation that we should be looking at.

**Comment by slaskawi** [comment]
@mwringe In that case I suggest looking into EAP official XPaaS images.

It looks like the documentation for 3.3 has [been moved](https://docs.openshift.com/container-platform/3.3/using_images/xpaas_images/index.html). Please have a look here: https://access.redhat.com/documentation/en/red-hat-xpaas/version-0/red-hat-xpaas-eap-image/

**Comment by lucasponce** [comment]
@slaskawi do you happen to know if the source code of the EAP xPaaS images are available ?
I can see that the EAP has a new layer under modules/system/layers/openshift where the kubernetes library is configured among other things.
I would like to see if can reuse that setup for wildfly too.
thanks !

**Comment by slaskawi** [comment]
@lucasponce @mwringe I think you confuse community projects and products, so let me try to explain...

Wildfly is a community equivalent of Red Hat's product called EAP. The same applies to Infinispan (which is an equivalent of a product called JDG) and OpenShift Origin, which is a community version of OpenShift Enterprise (OSE). Products are built on top of community bits but offer better stability, support, access to Knowledge Base etc. Of course, those are paid things, so you need to have an active subscription.

So back to the question - if you have an active subscription, I'd recommend [this page](https://access.redhat.com/products/red-hat-openshift-container-platform/) as a starting point. If you'd like to stick with the community bits - you have to do most of the work by your own or ask other community member (using forums, mailing lists) for help.

Having this in mind let me clarify the relation between Infinispan and Wildfly in the context of my tutorial... 

As far as I know, Wildfly (community app server) does not support Kubernetes deployment out of the box. We implemented this for Infinispan [here](https://github.com/infinispan/infinispan/pull/4448). Since Infinispan Server is built on top of Wildfly, I guess you could try to do exactly the same - add proper module and configure JGroups to use `KUBE_PING`. But to be honest, I haven't tried it.

I hope that helps :)

**Comment by slaskawi** [comment]
Discussed off-list.
