### ISSUE TITLE
KUBE_PING should extend TCPPING

### ISSUE THREAD

**Issue by slaskawi** [jgroups-extras/jgroups-kubernetes#23]
To reuse most of the logic there. The fix should also remove the HTTP Servers.

**Comment by belaban** [comment]
The idea is to use client.getPods() to retrieve all IP addresses of all pods. Then, instead of sending discovery requests to the web servers at 8888, we send them directly to the members at the given bind ports (plus port_range). 

This allows us to remove the web server.

The new KUBE_PING2 protocol will probably extend `TCPPING`, so the logic of the parent class can be reused.

**Comment by belaban** [comment]
Done - still needs some testing with minikube

**Comment by belaban** [comment]
Tests were successful with Minikube, documentation is in the readme.adoc

**Comment by tsegismont** [comment]
Thanks Bela, I'll try it next week.

2017-04-26 19:56 GMT+05:30 Bela Ban <notifications@github.com>:

**Comment by slaskawi** [comment]
+1000! that's a tremendous step forward!

**Comment by belaban** [comment]
I also tested KUBE_PING on Google Container Engine (GKE), as it works the same as on minikube. Let me know if you find any flaws when testing it yourself.

**Comment by tsegismont** [comment]
Will do. This was required to enable S2I builds with vertx-infinispan.
Thank you for looking into this!

2017-04-28 16:37 GMT+05:30 Bela Ban <notifications@github.com>:
